remote_theme: yggilabs/store-theme
introduction: This is the home of YggiGames. Here you will find the results of tinkering with, hacking and creating various games. Some of what you find here may even be tested. Enjoy!
footer: Made with ☕ in Minneapolis. &copy;2018  Sam Kelley

# manifest file stuff
short_name: Yggi Games
name: Yggi Games Blog
theme_color: "#DB3B1E"

# seo stuff
# @see https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: YggiGames Blog
description: The newest creations from YggiGames
# url: # default: site.github.url
author: Sam Kelley
# twitter:
#   username: benbalter
#   card: summary
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234
logo: /images/icon.svg
# social:
#   name: Ben Balter
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://plus.google.com/+BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter
# google_site_verification:
# webmaster_verifications:
#   google: 1234
#   bing: 1234
#   alexa: 1234
#   yandex: 1234
#   baidu: 1234
# lang: # default: en_US

permalink: none
analytics: false # url parameters are acting wierd
collections:
  products:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed
