---
title: Shop Demo
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  products:
    title: Products
    output: true
  uploads:
    title: Uploads
    output: true
  views:
    title: Views
    output: true
defaults:
- scope:
    path: ''
    type: products
  values:
    layout: product
- scope:
    path: ''
    type: views
  values:
    layout: shop
    title: Shop
short_name: Shop Demo
name: Shop Demo
theme_color: "#3b1edb"
description: A sample implementation of the shop
url: 
author: Sam Kelley
logo: "/assets/images/icon.svg"
lang: en_US
permalink: pretty
analytics: false
plugins:
- jekyll-seo-tag
- jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed
remote_theme: yggilabs/store-theme
