# manifest file stuff
short_name: 
name: 
theme_color: "#3b1edb"

# seo stuff
# @see https://github.com/jekyll/jekyll-seo-tag/blob/master/docs/usage.md
title: Shop Demo
description: A sample implementation of the shop
url: site.github.url # default: site.github.url
author: Sam Kelley
# twitter:
#   username: benbalter
#   card: summary
# facebook:
#   app_id: 1234
#   publisher: 1234
#   admins: 1234
logo: /assets/images/icon.svg
# social:
#   name: Ben Balter
#   links:
#     - https://twitter.com/BenBalter
#     - https://www.facebook.com/ben.balter
#     - https://www.linkedin.com/in/BenBalter
#     - https://plus.google.com/+BenBalter
#     - https://github.com/benbalter
#     - https://keybase.io/benbalter
# google_site_verification:
lang: en_US # default: en_US

permalink: none
analytics: false # url parameters are acting wierd
collections:
  products:
    output: true
defaults:
  -
    scope:
      path: ""
      type: "products"
    values:
      layout: "product"
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
sass:
  sass_dir: _sass
  style: compressed
remote_theme: yggilabs/store-theme
