---
label: product
hide_body: false
is_partial: false
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: name
  label: Name
  type: text
  hidden: false
  default: ''
- name: price
  label: Price
  type: text
  hidden: false
  default: ''
- type: image_gallery
  name: carousel_images
  label: carousel images
  description: a list of images shown in the product carousel
- name: features
  label: Features
  type: list
  hidden: false
  default: ''
- name: attributes
  label: Attributes
  type: field_group_list
  fields:
  - name: name
    label: Name
    type: text
    hidden: false
    default: ''
  - type: list
    name: ''
    label: ''
  hidden: false
  default: ''
pages:
- _products/product-1.md
