---
---

---
label: product
hide_body: 
is_partial: 
fields:
- name: title
  label: Title
  type: text
  hidden: false
  default: ''
- name: name
  label: Name
  type: text
  hidden: false
  default: ''
- name: price
  label: Price
  type: text
  hidden: false
  default: ''
- name: images
  label: Images
  type: list
  hidden: false
  default: ''
- name: features
  label: Features
  type: list
  hidden: false
  default: ''
- name: attributes
  label: Attributes
  type: field_group_list
  fields:
  - name: name
    label: Name
    type: text
    hidden: false
    default: ''
  - name: items
    label: Items
    type: list
    hidden: false
    default: ''
  hidden: false
  default: ''
